lobby-db:
  build: ./db
  ports:
    - "3308:3306"

lobby-ms:
  build: .
  command: bundle exec rails s -p 4010 -b '0.0.0.0'
  ports:
    - "4010:4010"
  links:
    - lobby-db
  environment:
    DB_USER: root
    DB_NAME: Lobby_MS
    DB_PASSWORD: root
